[book]
authors = ["mcpp-community"]
language = "en"
multilingual = false
src = "src"
title = "D2MySTL | A Mini STL Tutorial from Scratch"

[output.html]
git-repository-url = "https://github.com/mcpp-community/d2mystl"
